# Generated by Django 4.2 on 2023-08-29 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_revuiew_review_review_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 29, 22, 45, 14, 673558, tzinfo=datetime.timezone.utc), verbose_name='Created_at'),
        ),
    ]
