# Generated by Django 4.2 on 2023-08-30 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 0, 51, 24, 410293, tzinfo=datetime.timezone.utc), verbose_name='Created_at'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.CharField(max_length=300, verbose_name='Review'),
        ),
    ]
