# Generated by Django 4.2 on 2023-08-30 02:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_review_created_at_alter_review_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 30, 2, 3, 39, 3509, tzinfo=datetime.timezone.utc), verbose_name='Created_at'),
        ),
    ]
