# Generated by Django 4.2 on 2023-08-31 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_review_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 23, 51, 10, 481708, tzinfo=datetime.timezone.utc), verbose_name='Created_at'),
        ),
    ]
