# Generated by Django 4.2 on 2023-10-05 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 5, 13, 59, 52, 996493, tzinfo=datetime.timezone.utc), verbose_name='Created_at'),
        ),
    ]
