# Generated by Django 4.2 on 2023-10-09 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_review_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 0, 16, 36, 737370, tzinfo=datetime.timezone.utc), verbose_name='Created_at'),
        ),
    ]
