# Generated by Django 4.2 on 2023-09-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='phones',
            new_name='phones_1',
        ),
        migrations.AddField(
            model_name='company',
            name='phones_2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
