# Generated by Django 4.2 on 2023-09-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_phones_company_phones_1_company_phones_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pinterest_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
