# Generated by Django 4.2 on 2023-09-08 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_company_pinterest_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='youtube_link',
        ),
    ]
