# Generated by Django 4.2 on 2023-10-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='IUYLS4ZV', max_length=20),
        ),
    ]
