# Generated by Django 4.2 on 2023-10-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartdetail',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='03O8RZ9W', max_length=20),
        ),
    ]
