# Generated by Django 4.2 on 2023-10-09 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_cartdetail_quantity_alter_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_coupon', to='orders.coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='DUUC0TPW', max_length=20),
        ),
    ]
