# Generated by Django 4.2 on 2023-10-09 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_after_coupon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='BLPHIE8O', max_length=20),
        ),
    ]
