# Generated by Django 4.2 on 2023-12-02 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_cart_total_after_coupon_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='STFAHK9T', max_length=20),
        ),
    ]
