# Generated by Django 5.0.2 on 2024-02-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='T505A5UY', max_length=20),
        ),
    ]
